### ISSUE TITLE
runtime error due to the AttributeError of Automaton object

### ISSUE THREAD

**Issue by fanweneddie** [stavros7167/distributed_protocol_completion#1]
Hi there, I have met a runtime error when running the test at base directory:

```
[distributed_protocol_completion]$ python2 driver.py -b ABP1 -s z3minimum -c -a 
Traceback (most recent call last):
  File "driver.py", line 11, in <module>
    import examples.abp
  File "distributed_protocol_completion/examples/abp.py", line 203, in <module>
    safety_monitor(),
  File "distributed_protocol_completion/examples/abp.py", line 185, in safety_monitor
    monitor.input_complete('error')
AttributeError: 'Automaton' object has no attribute 'input_complete'
```
I think it is because method `input_complete()` is not defined in class `Automaton` in `automaton.py`. Could you please tell me how to solve this problem? Thanks a lot!

**Comment by stavros7167** [comment]
I'm afraid i can't help with this but perhaps Christos, the author of this software, can?
